/**
 * generate-card-effects-docs.mts
 *
 * Generates Card Effects markdown files for all 15 playable sets.
 * Output: workspace-root/Card Effects/<Set Name>/<Set Name> Card Effects.md
 *
 * Usage:  npx tsx scripts/generate-card-effects-docs.mts
 *
 * Files are OVERWRITTEN on each run — do not hand-edit them.
 * To change card descriptions, edit the source .ts card files and run this
 * script again (or `npm run docs:cards`).
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import '../src/cards/RegistryBoot.ts';
import { CardRegistry } from '../src/cards/CardRegistry.ts';
import {
  getCanonicalCardDescription,
  getCanonicalAttackDescription,
  getCanonicalActivatedAbilityDescription,
} from '../src/ui/cardStatSummary.ts';
import type { CardDefinition, SeraphimDefinition, AngelDefinition } from '../src/types/cards.ts';

// ---------------------------------------------------------------------------
// Per-set metadata
// ---------------------------------------------------------------------------

interface SetMeta {
  element: string;
  displayName: string;
  folderName: string;
  mechLine: string;
  resourceSummary: string;
}

const SETS: SetMeta[] = [
  {
    element: 'Neutrality',
    displayName: 'Neutrality',
    folderName: 'Neutrality',
    mechLine: 'Patience · Equilibrium Sigils · Patient Light',
    resourceSummary:
      '**Patience** — +1 per card played while Seraphim/Angels are on board; cashed out on attack (+15 Oblivion per stack, bonus draw at threshold). ' +
      '**Equilibrium Sigils** — conditional Patience amplification. ' +
      '**Patient Light** — diminishing-returns Patience-per-card bonus. ' +
      '**Vessel** — highest-Patience Seraphim designation.',
  },
  {
    element: 'Fire',
    displayName: 'Pyroabyss',
    folderName: 'Pyroabyss',
    mechLine: 'Heat · Chroma Embers · Inferno Tiers (Eternal/Infinite)',
    resourceSummary:
      '**Heat** — primary resource; gained by Stoke cards, spent by Burst cards for large Oblivion. ' +
      '**Chroma Embers** (Eternal/Infinite set-secondary) — quadratic Oblivion when ignited. ' +
      '**Inferno Tiers** (Eternal/Infinite eternal stack) — permanent per-Tier amp on Eternal/Infinite attacks.',
  },
  {
    element: 'Light',
    displayName: 'Heavenly Light',
    folderName: 'Heavenly Light',
    mechLine: 'Radiance · Halo Resonance (Eternal/Infinite)',
    resourceSummary:
      '**Radiance** — gained and spent each turn; spending triggers light burst effects. ' +
      '**Halo** (Eternal/Infinite eternal stack) — raised by Eternal cards, cashed out via Duality choice effects. ' +
      '**Halo Resonance** (Eternal/Infinite set-secondary) — raises the chain floor on cashout.',
  },
  {
    element: 'Thornbound',
    displayName: 'Thornbound Plains',
    folderName: 'Thornbound Plains',
    mechLine: 'Trail · Scar · Briar Spiral (Eternal/Infinite)',
    resourceSummary:
      '**Trail** — generated by playing cards; manually convert to Scar in the HUD. ' +
      '**Scar** — feeds conditional thresholds on Seraphim attacks. ' +
      '**Thorncrown** (Eternal/Infinite eternal stack) — raised each Eternal play. ' +
      '**Briar Spiral** (Eternal/Infinite set-secondary) — converts into Trail and scales chain with Trail.',
  },
  {
    element: 'Mechanical',
    displayName: 'Mechanical Dreams',
    folderName: 'Mechanical Dreams',
    mechLine: 'Strain · Resonance Charge · Reactor Core (Eternal/Infinite)',
    resourceSummary:
      '**Strain** — built up and vented; Overclock effects spend Strain for bonus effects. ' +
      '**Resonance Charge** — triggers threshold conditions for Seraphim and Cherubim buffs. ' +
      '**Reactor Core** (Eternal/Infinite eternal stack + set-secondary) — Mechanical Eternal/Infinite signature stack.',
  },
  {
    element: 'Prismatic',
    displayName: 'Prismatic Accord',
    folderName: 'Prismatic Accord',
    mechLine: 'Prismatic Light · Prism Charges · Refraction Depth · Mirror Chain (Eternal/Infinite)',
    resourceSummary:
      '**Prismatic Light** — switch-channel resource. ' +
      '**Prism Charges** — fixed-amount spends for payoff effects. ' +
      '**Refraction Depth** — tracks channel switches this turn; conditions gated on depth ≥ N. ' +
      '**Mirror Chain** (Eternal/Infinite eternal stack) — Spectrum Echo set-secondary scales Oblivion by distinct channels.',
  },
  {
    element: 'Dark',
    displayName: 'Black Glass Inferno',
    folderName: 'Black Glass Inferno',
    mechLine: 'White Flame · Black Flame · Fracture · Eclipse Mark (Eternal/Infinite)',
    resourceSummary:
      '**White Flame** and **Black Flame** — balance-sensitive twin resources; swapping them unlocks bonus thresholds. ' +
      '**Monochromatic Shards** — supplementary Oblivion resource. ' +
      '**Fracture** — conditional amplifier for Eclipse burst effects. ' +
      '**Eclipse Mark** (Eternal/Infinite eternal stack) — accumulates during Eternal plays, cashed out as Eclipse Burst. ' +
      '**Veil Shard** (Eternal/Infinite set-secondary) — BGI Eternal/Infinite signature set-secondary.',
  },
  {
    element: 'Snowbound',
    displayName: 'Snowbound Voltage',
    folderName: 'Snowbound Voltage',
    mechLine: 'Arctic Charge · Voltage Surge / Polar Capacitor (Eternal/Infinite)',
    resourceSummary:
      '**Arctic Charge** — Frost cards gain it, Voltage cards discharge it for Oblivion. ' +
      '**Voltage Surge** (Eternal/Infinite eternal stack) — raised by Eternal Voltage plays. ' +
      '**Polar Capacitor** (Eternal/Infinite set-secondary) — bank-and-release: Voltage mode → Oblivion per capacitor; Frost mode → Arctic Charge per capacitor.',
  },
  {
    element: 'GlassAbsolute',
    displayName: 'Glass Absolute',
    folderName: 'Glass Absolute',
    mechLine: 'Glass Fragments · Proof Cascade / Refraction Charge (Eternal/Infinite)',
    resourceSummary:
      '**Glass board presence** — dense Seraphim/Cherubim placement unlocks fragment-tier conditions. ' +
      '**Absol (set_secondary kind)** — tracked per Eternal/Infinite play as Refraction Charge. ' +
      '**Proof Cascade** (Eternal/Infinite eternal stack) — accumulated proof depth amplifies Oblivion per proof depth tier. ' +
      '**Refraction Charge** (Eternal/Infinite set-secondary) — Glass Eternal conversion threshold riders.',
  },
  {
    element: 'BlazingGarden',
    displayName: 'Blazing Garden',
    folderName: 'Blazing Garden',
    mechLine: 'Bloom · Burn Lineages · Grove · Wild Pollen (Eternal/Infinite)',
    resourceSummary:
      '**Bloom** — harvested for Oblivion bonuses. ' +
      '**Burn Lineages** — cards enter Burn phase; charred cards seed Ember Grove. ' +
      '**Wild Pollen** (Eternal/Infinite set-secondary) — seeded by Eternal cards, spent for scaled Oblivion + score mult per Bloom. ' +
      '**Garden Law** — global modifier (Rose/Sunflower/Thistle) applied by Eternal/Infinite cards.',
  },
  {
    element: 'Butterfly',
    displayName: 'Age of the Butterfly',
    folderName: 'Age of the Butterfly',
    mechLine: 'Flutter Spectrum · Wing Pulse · Wing Resonance (Eternal/Infinite)',
    resourceSummary:
      '**Flutter Spectrum** — charged by Ophanim, released for Oblivion bursts. ' +
      '**Wing Pulse** (set-secondary kind: flutter) — doubles next N Spectrum gains. ' +
      '**Wing Resonance** (Eternal/Infinite eternal stack) — Harmonize/Apex cashouts scale with resonance count and Formation bonuses.',
  },
  {
    element: 'EternalSeas',
    displayName: 'Eternal Seas',
    folderName: 'Eternal Seas',
    mechLine: 'Undertow · Foam · Deepwake / Tide Echo (Eternal/Infinite)',
    resourceSummary:
      '**Undertow** — built during the turn, released for Oblivion. ' +
      '**Foam** — accumulated alongside Undertow; spend 5 Foam (HUD) to draw 1 card. ' +
      '**Deepwake** (Eternal/Infinite eternal stack) — surge effects generate Undertow then immediately release it. ' +
      '**Tide Echo** (Eternal/Infinite set-secondary) — polarity-split cashout based on Undertow/Foam balance.',
  },
  {
    element: 'AbyssalForge',
    displayName: 'Abyssal Forge',
    folderName: 'Abyssal Forge',
    mechLine: 'Reforge Charges · Pearls · Imprint · Forge Crown (Eternal/Infinite)',
    resourceSummary:
      '**Reforge Charges** — fuel recast effects that replay previous cards at scaled power. ' +
      '**Pearls** — dropped by Forge cards, cashed out for Oblivion. ' +
      '**Imprint** — placed on played cards; spent for burst Oblivion or empowered recasts. ' +
      '**Forge Crown** (Eternal/Infinite eternal stack) — accumulates via Eternal plays, cashed out for large Oblivion.',
  },
  {
    element: 'DeathFlamedHell',
    displayName: 'Death-flamed Hell',
    folderName: 'Death-flamed Hell',
    mechLine: 'Pyre Embers · Cinder Crowns · Veil Marks',
    resourceSummary:
      '**Pyre Embers** (eternal stack: pyre) — accumulates via Seraphim and Ophanim plays. ' +
      '**Cinder Crowns** (set-secondary: pyre) — stacked for conditional bonuses, spent for Oblivion cashouts. ' +
      '**Veil Marks** — transmuted from Embers/Crowns via Eternal/Infinite effects; cashed out for massive Oblivion. ' +
      'DFH has **no MCB overrides** — source attack descriptions are the live game values.',
  },
  {
    element: 'WishedUponAStar',
    displayName: 'Wished Upon a Star',
    folderName: 'Wished Upon a Star',
    mechLine: 'Starlight Charges · Dream Lattice · Star Crowns (Eternal/Infinite)',
    resourceSummary:
      '**Starlight Charges** — base currency; drives Nova Wish Burst Oblivion formula. ' +
      '**Dream Lattice** — amplifier multiplier for Nova Wish Burst (Oblivion = Starlight × (1 + Dream × coeff)). ' +
      '**Star Crowns** (Eternal/Infinite eternal stack) — cashed out via Constellation Lock Release. ' +
      'This is the **event set** — accessed through special packs.',
  },
];

// ---------------------------------------------------------------------------
// Shared rendering helpers (same logic as Neutrality preview)
// ---------------------------------------------------------------------------

type Tier = 'Common' | 'Rare' | 'Epic' | 'Legendary' | 'Eternal' | 'Infinite';
const TIER_ORDER: Tier[] = ['Common', 'Rare', 'Epic', 'Legendary', 'Eternal', 'Infinite'];
const TYPE_ORDER = ['Ophanim', 'Seraphim', 'Cherubim', 'Angel'];

function rarityGlyph(rarity: string): string {
  switch (rarity) {
    case 'Common':   return '◈';
    case 'Rare':     return '◆';
    case 'Epic':     return '✦';
    case 'Legendary': return '★';
    case 'Eternal':  return '♾';
    case 'Infinite': return '∞';
    default:         return '·';
  }
}

function descriptionFor(card: CardDefinition): string {
  try {
    const canon = getCanonicalCardDescription(card as Parameters<typeof getCanonicalCardDescription>[0]);
    if (canon && !canon.includes('undefined')) return canon;
  } catch { /* fall through */ }
  return card.description ?? '(no description)';
}

function formatSeraphimAttacks(card: SeraphimDefinition): string {
  const attacks = card.attacks;
  if (!attacks) return '';
  const unsyn = getCanonicalAttackDescription(attacks.unsynergized);
  const syn   = getCanonicalAttackDescription(attacks.synergized);
  return [
    `  - **${attacks.unsynergized.name}** (Unsynergized): ${unsyn}`,
    `  - **${attacks.synergized.name}** (Synergized): ${syn}`,
  ].join('\n');
}

function formatAngelCard(card: AngelDefinition): string {
  const parts: string[] = [];

  // Summon cost
  const costNames = card.summonCost.map(id => CardRegistry.get(id)?.name ?? id);
  parts.push('**Summon**: ' + costNames.join(' + '));

  // Activated ability
  if (card.activatedAbility) {
    let abilityText = card.activatedAbility.description;
    try {
      const canon = getCanonicalActivatedAbilityDescription(card as Parameters<typeof getCanonicalActivatedAbilityDescription>[0]);
      if (canon && !canon.includes('undefined')) abilityText = canon;
    } catch { /* keep authored */ }
    parts.push(`**Ability (${card.activatedAbility.name})**: After ${card.activatedAbility.cardsPlayedRequirement} cards played: ${abilityText}`);
  }

  // Attacks
  if (card.attacks) {
    const primary = getCanonicalAttackDescription(card.attacks.primary);
    const exalted = getCanonicalAttackDescription(card.attacks.exalted);
    parts.push(
      '**Attacks**:',
      `  - **${card.attacks.primary.name}** (Primary): ${primary}`,
      `  - **${card.attacks.exalted.name}** (Exalted): ${exalted}`,
    );
  }

  return parts.join('\n\n');
}

function renderCard(card: CardDefinition): string {
  const glyph = rarityGlyph(card.rarity);
  const lines: string[] = [
    `### ${glyph} ${card.name} \`${card.definitionId}\``,
    `**Rarity**: ${card.rarity} · **Type**: ${card.type}`,
    '',
    descriptionFor(card),
  ];

  if (card.type === 'Seraphim' && (card as SeraphimDefinition).attacks) {
    const attackLines = formatSeraphimAttacks(card as SeraphimDefinition);
    if (attackLines) {
      lines.push('', '**Attacks**:', attackLines);
    }
  }

  if (card.type === 'Angel') {
    lines.push('', formatAngelCard(card as AngelDefinition));
  }

  return lines.join('\n');
}

function renderGroup(type: string, cards: CardDefinition[]): string {
  const sorted = [...cards].sort((a, b) => {
    const ra = TIER_ORDER.indexOf(a.rarity as Tier);
    const rb = TIER_ORDER.indexOf(b.rarity as Tier);
    return ra !== rb ? ra - rb : a.name.localeCompare(b.name);
  });

  return [
    `## ${type}s`,
    '',
    ...sorted.flatMap(card => [renderCard(card), '', '---', '']),
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Per-set document builder
// ---------------------------------------------------------------------------

function buildSetDoc(meta: SetMeta, allCards: CardDefinition[]): string {
  const setCards = allCards.filter(c => c.element === meta.element);
  if (setCards.length === 0) return '';

  const baseCards    = setCards.filter(c => c.rarity !== 'Eternal' && c.rarity !== 'Infinite');
  const eternalCards = setCards.filter(c => c.rarity === 'Eternal');
  const infiniteCards = setCards.filter(c => c.rarity === 'Infinite');

  // Group base cards by type
  const byType = new Map<string, CardDefinition[]>();
  for (const card of baseCards) {
    const t = card.type;
    if (!byType.has(t)) byType.set(t, []);
    byType.get(t)!.push(card);
  }

  const sections: string[] = [
    `# ${meta.displayName} — Card Effects`,
    '',
    `> **Set**: ${meta.displayName} · **Element**: \`${meta.element}\``,
    `> **Mechanics**: ${meta.mechLine}`,
    `>`,
    `> ${meta.resourceSummary}`,
    '',
    `> *Auto-generated from \`CardRegistry\`. Run \`npm run docs:cards\` to refresh.*`,
    '',
  ];

  for (const type of TYPE_ORDER) {
    const cards = byType.get(type);
    if (cards && cards.length > 0) {
      sections.push(renderGroup(type, cards));
    }
  }

  if (eternalCards.length > 0) {
    sections.push('# Eternal Tier', '');
    const etByType = new Map<string, CardDefinition[]>();
    for (const c of eternalCards) {
      if (!etByType.has(c.type)) etByType.set(c.type, []);
      etByType.get(c.type)!.push(c);
    }
    for (const type of TYPE_ORDER) {
      const cards = etByType.get(type);
      if (cards && cards.length > 0) sections.push(renderGroup(type, cards));
    }
  }

  if (infiniteCards.length > 0) {
    sections.push('# Infinite Tier', '');
    const infByType = new Map<string, CardDefinition[]>();
    for (const c of infiniteCards) {
      if (!infByType.has(c.type)) infByType.set(c.type, []);
      infByType.get(c.type)!.push(c);
    }
    for (const type of TYPE_ORDER) {
      const cards = infByType.get(type);
      if (cards && cards.length > 0) sections.push(renderGroup(type, cards));
    }
  }

  return sections.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const allCards = CardRegistry.getAll();
let generated = 0;

for (const meta of SETS) {
  const doc = buildSetDoc(meta, allCards);
  if (!doc) {
    console.log(`  (skipped ${meta.displayName} — no cards found for element '${meta.element}')`);
    continue;
  }

  const dir  = resolve('..', 'Card Effects', meta.folderName);
  const file = resolve(dir, `${meta.folderName} Card Effects.md`);
  mkdirSync(dir, { recursive: true });
  writeFileSync(file, doc, { encoding: 'utf8' });

  const count = allCards.filter(c => c.element === meta.element).length;
  console.log(`  ✓ ${meta.displayName} (${count} cards) → ${file}`);
  generated++;
}

console.log(`\nDone — generated ${generated}/${SETS.length} sets.`);
