import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { CardRegistry } from '../src/cards/CardRegistry';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');
const outFile = path.join(repoRoot, 'src/data/cards/materializedCardBalance.ts');

type BalanceEntry =
  | { type: 'Seraphim'; attacks: unknown; attackTags: string[] }
  | { type: 'Angel'; attacks: unknown; attackTags: string[] }
  | { type: 'Cherubim'; effects: unknown }
  | { type: 'Ophanim'; effects: unknown };

const defs = CardRegistry.getAll();
const balance: Record<string, BalanceEntry> = {};

for (const def of defs) {
  switch (def.type) {
    case 'Seraphim': {
      balance[def.definitionId] = {
        type: 'Seraphim',
        attacks: def.attacks ?? null,
        attackTags: [...(def.attackTags ?? [])],
      };
      break;
    }
    case 'Angel': {
      balance[def.definitionId] = {
        type: 'Angel',
        attacks: def.attacks ?? null,
        attackTags: [...(def.attackTags ?? [])],
      };
      break;
    }
    case 'Cherubim': {
      balance[def.definitionId] = {
        type: 'Cherubim',
        effects: def.effects,
      };
      break;
    }
    case 'Ophanim': {
      balance[def.definitionId] = {
        type: 'Ophanim',
        effects: def.effects,
      };
      break;
    }
    default:
      break;
  }
}

const sorted = Object.fromEntries(
  Object.entries(balance).sort(([a], [b]) => a.localeCompare(b)),
);

const file = `/* Auto-generated by scripts/generate-card-balance-overrides.mts. Do not edit manually. */\n\nexport const MATERIALIZED_CARD_BALANCE = ${JSON.stringify(sorted, null, 2)} as const;\n`;

fs.writeFileSync(outFile, file, 'utf8');
console.log(`Wrote ${Object.keys(sorted).length} balance entries to ${path.relative(repoRoot, outFile)}`);
