/**
 * Wished Upon A Star — Event Landing Page
 *
 * Presents the set story, pack purchase tile (using Aberrated Shards),
 * a Starlight/Dream Lattice mechanic primer, and quick-links to the
 * relevant Eternity's Wake bosses.
 */

import React, { useEffect, useState } from 'react';
import { useStore } from '@/state/store';
import { uiTypography } from '@/ui/theme';
import { PACK_DEFINITIONS } from '@/data/packs/packDefinitions';
import { BOSS_DEFINITIONS, getBossDisplayHp } from '@/data/bosses/bossDefinitions';
import { formatCountdown, getWuasEventCountdown, WUAS_EVENT_ENDS_LABEL } from '@/ui/eventWishedUponAStar/eventTimer';

interface Props {
  onClose: () => void;
  onCardStore: () => void;
  onEternitysWake: () => void;
}

function getEventTheme() {
  return {
    background:
      'radial-gradient(circle at 18% -12%, rgba(133, 232, 255, 0.26) 0%, rgba(133, 232, 255, 0) 42%), radial-gradient(circle at 82% 112%, rgba(173, 130, 255, 0.24) 0%, rgba(173, 130, 255, 0) 48%), linear-gradient(180deg, rgba(3, 4, 16, 0.98) 0%, rgba(6, 8, 24, 0.99) 46%, rgba(2, 3, 12, 1) 100%)',
    accent: '#8de6ff',
    accentSoft: '#d7b7ff',
    border: 'rgba(138, 221, 255, 0.58)',
    panel: 'rgba(8, 14, 36, 0.86)',
    panelStrong: 'rgba(12, 18, 46, 0.94)',
    text: '#eef4ff',
    textMuted: 'rgba(211, 223, 250, 0.84)',
    textFaint: 'rgba(183, 200, 236, 0.66)',
    glowShadow: '0 14px 32px rgba(84, 186, 255, 0.24)',
    glowColor: 'rgba(141, 230, 255, 0.42)',
    success: '#90e9ba',
    danger: '#ff9fb6',
    reward: '#ffd58c',
  };
}

const MECHANIC_ROWS: { label: string; desc: string }[] = [
  { label: 'Starlight Charges', desc: 'Primary WUAS scaling resource. Generated by multiple WUAS effects and board passives, then spent by finishers and burst effects.' },
  { label: 'Dream Lattice',     desc: 'Secondary amplifier used by several WUAS cards. It usually resets at turn end unless specifically preserved by card effects.' },
  { label: 'Nova Wish Burst',   desc: 'WUAS burst action that converts setup into Oblivion. Exact scaling and triggers vary by card — check each card text for live values.' },
  { label: 'Star Crowns',       desc: 'Eternal-layer WUAS stack resource. Some cards bank Star Crowns while others spend or cash them out for payoff turns.' },
  { label: 'Infinite Starbirth', desc: 'Infinite-layer WUAS payoff line tied to your board state plus WUAS setup counters.' },
  { label: 'Execution Window',  desc: 'Most WUAS turns are setup-first, burst-later. Build counters with low-risk plays, then convert everything in one attack window.' },
];

const overlay: React.CSSProperties = {
  position: 'absolute',
  inset: 0,
  zIndex: 30,
  display: 'flex',
  flexDirection: 'column',
  overflow: 'hidden',
  fontFamily: uiTypography.body,
};

export default function WishedUponAStarEvent({ onClose, onCardStore, onEternitysWake }: Props) {
  const C = getEventTheme();
  const shards = useStore(s => s.progress.aberratedShards);
  const progress = useStore(s => s.progress);
  const [activeTab, setActiveTab] = useState<'story' | 'mechanic' | 'packs' | 'bosses'>('story');
  const [nowMs, setNowMs] = useState<number>(() => Date.now());

  useEffect(() => {
    const id = window.setInterval(() => setNowMs(Date.now()), 1000);
    return () => window.clearInterval(id);
  }, []);

  const eventCountdown = formatCountdown(getWuasEventCountdown(nowMs));

  const wuasPack = PACK_DEFINITIONS.find(p => p.id === 'pack-wished-upon-a-star');
  const wuasBosses = BOSS_DEFINITIONS.filter(b => b.category === '[EVENT] Wished Upon A Star');

  return (
    <div style={{ ...overlay, background: C.background }}>
      {/* Header */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '18px 28px',
        borderBottom: `1px solid ${C.border}`,
        background: C.panelStrong,
        backdropFilter: 'blur(6px)',
        flexShrink: 0,
      }}>
        <div>
          <div style={{ fontFamily: uiTypography.display, fontSize: 22, letterSpacing: 3, textTransform: 'uppercase', color: C.accent, textShadow: `0 0 26px ${C.glowColor}` }}>
            ✦ Wished Upon A Star ✦
          </div>
          <div style={{ fontSize: 11, color: C.textMuted, letterSpacing: 1.2, marginTop: 3 }}>
            [EVENT SET] · The Wishwright's Age · Stellar Wish System
          </div>
          <div style={{ fontSize: 11, color: C.accentSoft, letterSpacing: 1, marginTop: 4 }}>
            Ends {WUAS_EVENT_ENDS_LABEL}
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 18 }}>
          <div style={{
            padding: '7px 12px',
            borderRadius: 999,
            border: `1px solid ${C.border}`,
            background: C.panel,
            fontSize: 11,
            fontFamily: uiTypography.display,
            letterSpacing: 1.1,
            color: C.accent,
            boxShadow: C.glowShadow,
          }}>
            Ends In {eventCountdown}
          </div>
          <div style={{ fontSize: 13, color: C.textMuted, letterSpacing: 0.8 }}>
            Aberrated Shards: <span style={{ color: C.accentSoft, fontWeight: 700 }}>{shards.toLocaleString()}</span>
          </div>
          <button
            onClick={onClose}
            style={{
              padding: '6px 18px', borderRadius: 6, fontSize: 12, cursor: 'pointer',
              fontFamily: uiTypography.body, letterSpacing: 0.8,
              background: C.panel, border: `1px solid ${C.border}`,
              color: C.accent,
            }}
          >
            ✕ Close
          </button>
        </div>
      </div>

      {/* Tab bar */}
      <div style={{ display: 'flex', borderBottom: `1px solid ${C.border}`, background: C.panel, flexShrink: 0 }}>
        {(['story', 'mechanic', 'packs', 'bosses'] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            style={{
              padding: '10px 24px', fontSize: 12, cursor: 'pointer', border: 'none', outline: 'none',
              fontFamily: uiTypography.display, letterSpacing: 1.4, textTransform: 'uppercase',
              background: activeTab === tab ? C.panelStrong : 'transparent',
              color: activeTab === tab ? C.accent : C.textFaint,
              borderBottom: activeTab === tab ? `2px solid ${C.accent}` : '2px solid transparent',
              transition: 'color 160ms, background 160ms',
            }}
          >
            {tab === 'story' ? 'Story' : tab === 'mechanic' ? 'Mechanic' : tab === 'packs' ? 'Pack' : 'Bosses'}
          </button>
        ))}
      </div>

      {/* Content */}
      <div style={{ flex: 1, overflow: 'auto', padding: '28px clamp(20px, 5vw, 64px)' }}>

        {activeTab === 'story' && (
          <div style={{ maxWidth: 720, margin: '0 auto' }}>
            <p style={{ fontSize: 15, lineHeight: 1.8, color: C.text, marginBottom: 20 }}>
              Before stars learned to fall, they made wishes of their own.
            </p>
            <p style={{ fontSize: 14, lineHeight: 1.8, color: C.textMuted, marginBottom: 16 }}>
              In the age before the first light cooled, three cosmic beings stood sentinel at the edge of
              creation: <em>Selenira</em>, whose vigil kept darkness patient; <em>Draethos</em>, whose gravity
              bent time into loops of longing; and <em>Aethervex</em>, the Wishwright, whose wings were made
              of galaxy-thread and whose eyes swallowed dead suns.
            </p>
            <p style={{ fontSize: 14, lineHeight: 1.8, color: C.textMuted, marginBottom: 16 }}>
              When the Wishwright's Age ended — not with a collapse but with a wish unfulfilled — their power
              scattered as <strong style={{ color: C.accent }}>Starlight Charges</strong> across every card
              played in the arena. Now their children walk as cards. Those who master the{' '}
              <strong style={{ color: C.accent }}>Dream Lattice</strong> can bend their wishes into
              oblivion nova-bursts capable of erasing entire boss phases.
            </p>
            <p style={{ fontSize: 14, lineHeight: 1.8, color: C.textMuted }}>
              The three Eternal forms — <em>Aethervex the Wishwright</em>, <em>Selenira Voidbane</em>, and{' '}
              <em>Draethos the Unforgotten</em> — now serve as the event's boss guardians. Defeat them in
              Eternity's Wake to claim their Eternal card rewards.
            </p>
          </div>
        )}

        {activeTab === 'mechanic' && (
          <div style={{ maxWidth: 780, margin: '0 auto' }}>
            <div style={{ fontSize: 13, color: C.textMuted, letterSpacing: 0.8, marginBottom: 20 }}>
              Wished Upon A Star is a setup-to-burst engine. Build Starlight Charges and Dream Lattice first, then cash out with WUAS finishers. For exact formulas, trust the live card text shown in your collection and on card panels.
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {MECHANIC_ROWS.map(({ label, desc }) => (
                <div key={label} style={{
                  padding: '14px 18px', borderRadius: 10,
                  border: `1px solid ${C.border}`,
                  background: C.panel,
                }}>
                  <div style={{ fontSize: 14, fontFamily: uiTypography.display, letterSpacing: 1.2, color: C.accent, marginBottom: 5 }}>
                    {label}
                  </div>
                  <div style={{ fontSize: 12, color: C.textMuted, lineHeight: 1.7 }}>
                    {desc}
                  </div>
                </div>
              ))}
            </div>
            <div style={{ marginTop: 24, padding: '14px 18px', borderRadius: 10, border: `1px solid ${C.border}`, background: C.panelStrong }}>
              <div style={{ fontSize: 13, fontFamily: uiTypography.display, letterSpacing: 1, color: C.text, marginBottom: 6 }}>Key Synergies</div>
              <ul style={{ fontSize: 12, color: C.textMuted, lineHeight: 1.8, paddingLeft: 20, margin: 0 }}>
                <li><strong>Early setup cards</strong> should be used to raise Starlight and Dream before you commit your burst pieces.</li>
                <li><strong>Board passives</strong> that add Starlight per card played are strongest when deployed before long play chains.</li>
                <li><strong>Dream-preserve effects</strong> enable multi-turn planning by carrying part of your setup into the next turn.</li>
                <li><strong>Star Crown cards</strong> usually perform best in two phases: bank first, then spend/cash out in a dedicated finish turn.</li>
                <li><strong>Infinite WUAS finishers</strong> are most efficient after both counters are already built and your board is established.</li>
                <li><strong>If a card text conflicts with this guide</strong>, the card text is authoritative and should be treated as the source of truth.</li>
              </ul>
            </div>
          </div>
        )}

        {activeTab === 'packs' && (
          <div style={{ maxWidth: 600, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 16 }}>
            {wuasPack ? (
              <div style={{
                padding: '22px 24px', borderRadius: 14,
                border: `1px solid ${C.border}`,
                background: C.panel,
                boxShadow: C.glowShadow,
              }}>
                <div style={{ fontFamily: uiTypography.display, fontSize: 17, letterSpacing: 1.6, color: C.accent, marginBottom: 6 }}>
                  {wuasPack.name}
                </div>
                <div style={{ fontSize: 12, color: C.textMuted, marginBottom: 16, lineHeight: 1.7 }}>
                  {wuasPack.description}
                </div>
                <div style={{ fontSize: 12, color: C.textFaint, marginBottom: 16 }}>
                  5 cards per pack · {wuasPack.cardPool.length} unique cards in the pool
                </div>
                <div style={{ fontSize: 13, color: C.textMuted, marginBottom: 16 }}>
                  Cost: <strong style={{ color: C.accent }}>{wuasPack.cost.toLocaleString()} Aberrated Shards</strong>
                  {' · '}
                  <span style={{ color: shards >= wuasPack.cost ? C.success : C.danger }}>
                    {shards >= wuasPack.cost ? `You can afford this (${shards.toLocaleString()} shards)` : `Need ${(wuasPack.cost - shards).toLocaleString()} more shards`}
                  </span>
                </div>
                <div style={{ marginBottom: 14, fontSize: 11, color: C.accentSoft, letterSpacing: 0.7 }}>
                  Event End: {WUAS_EVENT_ENDS_LABEL} · Time Left: {eventCountdown}
                </div>
                <button
                  onClick={onCardStore}
                  style={{
                    padding: '10px 22px', borderRadius: 8, fontSize: 13, cursor: 'pointer',
                    fontFamily: uiTypography.display, letterSpacing: 1.2,
                    background: C.panelStrong, border: `1px solid ${C.border}`,
                    color: C.accent, width: '100%',
                  }}
                >
                  Open in Card Store →
                </button>
              </div>
            ) : (
              <div style={{ color: C.textFaint, fontSize: 13 }}>
                Pack data not yet available.
              </div>
            )}
            <div style={{ padding: '14px 18px', borderRadius: 10, border: `1px solid ${C.border}`, background: C.panelStrong, fontSize: 12, color: C.textMuted, lineHeight: 1.7 }}>
              <strong style={{ color: C.accent }}>Earning Aberrated Shards:</strong> Shards are awarded from boss fights, daily rewards, achievement completions, and event milestones. They are an event-exclusive currency and do not interact with the standard Oblivion economy.
            </div>
          </div>
        )}

        {activeTab === 'bosses' && (
          <div style={{ maxWidth: 720, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 12 }}>
            <div style={{ fontSize: 12, color: C.textFaint, marginBottom: 4 }}>
              Defeat these bosses in Eternity's Wake to claim their Eternal card rewards.
            </div>
            {wuasBosses.length === 0 ? (
              <div style={{ color: C.textFaint, fontSize: 13 }}>
                No bosses registered for this event yet.
              </div>
            ) : (
              wuasBosses.map(boss => (
                <div key={boss.id} style={{
                  display: 'flex', alignItems: 'center', gap: 16,
                  padding: '14px 18px', borderRadius: 10,
                  border: `1px solid ${C.border}`,
                  background: C.panel,
                }}>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontFamily: uiTypography.display, fontSize: 14, letterSpacing: 1.2, color: C.accent, marginBottom: 4 }}>
                      {boss.name}
                    </div>
                    <div style={{ fontSize: 11, color: C.textMuted, lineHeight: 1.6 }}>
                      {boss.description}
                    </div>
                  </div>
                  <div style={{ fontSize: 11, color: C.textFaint, textAlign: 'right', flexShrink: 0 }}>
                    <div>HP: {getBossDisplayHp(progress, boss).toLocaleString()}</div>
                    <div style={{ color: C.reward, marginTop: 2 }}>+{boss.firstClearShards} shards (first clear)</div>
                    <div style={{ color: C.textMuted }}>+{boss.repeatClearShards} shards (repeat)</div>
                  </div>
                </div>
              ))
            )}
            <button
              onClick={onEternitysWake}
              style={{
                marginTop: 8, padding: '10px 22px', borderRadius: 8, fontSize: 13, cursor: 'pointer',
                fontFamily: uiTypography.display, letterSpacing: 1.2,
                background: C.panelStrong, border: `1px solid ${C.border}`,
                color: C.accent,
              }}
            >
              Go to Eternity's Wake →
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
