-- =============================================================================
-- 0019_coop_session_events.sql
-- Durable event log for host-authoritative co-op session sync/replay.
-- =============================================================================

create or replace function public.can_access_coop_session(session_uuid uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.coop_raid_sessions crs
    where crs.id = session_uuid
      and (crs.host_id = auth.uid() or crs.guest_id = auth.uid())
  )
  or exists (
    select 1
    from public.eternity_wake_coop_sessions ewcs
    where ewcs.id = session_uuid
      and (
        ewcs.host_id = auth.uid()
        or auth.uid() = any(ewcs.invited_user_ids)
        or auth.uid() = any(ewcs.accepted_user_ids)
      )
  )
  or exists (
    select 1
    from public.party_sessions ps
    where ps.id = session_uuid
      and (ps.host_user = auth.uid() or auth.uid() = any(ps.participant_user_ids))
  );
$$;

create table if not exists public.coop_session_events (
  id                bigint generated by default as identity primary key,
  session_id        uuid not null,
  sender_user       uuid not null references public.profiles(id) on delete cascade,
  protocol_version  int not null default 1,
  event_type        text not null,
  payload           jsonb not null default '{}'::jsonb,
  created_at        timestamptz not null default now()
);

create index if not exists coop_session_events_session_seq_idx
  on public.coop_session_events (session_id, id);

create index if not exists coop_session_events_session_created_idx
  on public.coop_session_events (session_id, created_at desc);

alter table public.coop_session_events enable row level security;

drop policy if exists coop_session_events_select on public.coop_session_events;
create policy coop_session_events_select
  on public.coop_session_events for select
  to authenticated
  using (public.can_access_coop_session(session_id));

drop policy if exists coop_session_events_insert on public.coop_session_events;
create policy coop_session_events_insert
  on public.coop_session_events for insert
  to authenticated
  with check (
    sender_user = auth.uid()
    and public.can_access_coop_session(session_id)
  );

-- Keep realtime publication in sync for optional postgres_changes consumers.
do $$
begin
  begin
    alter publication supabase_realtime add table public.coop_session_events;
  exception
    when duplicate_object then null;
  end;
end $$;